import {requireStaff} from "@/lib/admin/auth";
import {createClient} from "@/lib/supabase/server";
import {deleteCategory,saveCategory} from "./actions";
type Props={searchParams:Promise<{error?:string;saved?:string;deleted?:string}>};
type Translation={locale:"fa"|"en";name:string;slug:string;description:string|null;seo_title:string|null;seo_description:string|null};
type Brand={id:number;code:string;name:string};
type Category={id:number;brand_id:number;code:string;icon_key:string;accent_color:string;position:number;is_published:boolean;translations:Translation[]};

export default async function ProductCategoriesPage({searchParams}:Props){
 const[{profile},query]=await Promise.all([requireStaff(),searchParams]);const supabase=await createClient();
 const[{data:brandRows=[]},{data:brandNames=[]},{data:categoryRows=[]}]=await Promise.all([supabase.from("brands").select("id,code").order("position"),supabase.from("brand_translations").select("brand_id,name").eq("locale","fa"),supabase.from("product_categories").select("id,brand_id,code,icon_key,accent_color,position,is_published").order("position")]);
 const{data:translations=[]}=categoryRows?.length?await supabase.from("product_category_translations").select("category_id,locale,name,slug,description,seo_title,seo_description").in("category_id",categoryRows.map(item=>item.id)):{data:[]};
 const brands:Brand[]=(brandRows??[]).map(item=>({...item,name:brandNames?.find(name=>name.brand_id===item.id)?.name||item.code}));
 const categories:Category[]=(categoryRows??[]).map(item=>({...item,translations:(translations??[]).filter(t=>t.category_id===item.id)}));
 return <main className="admin-module-page admin-categories-page"><header><div><div><small>کاتالوگ</small><h1>دسته‌های محصول</h1><p>ساختار محصولات بر اساس برند</p></div></div></header>
 {query.error?<p className="admin-alert error" role="alert">{query.error}</p>:null}{query.saved?<p className="admin-alert success">دسته ذخیره شد.</p>:null}{query.deleted?<p className="admin-alert success">دسته حذف شد.</p>:null}
 <section className="admin-brand-create"><header><h2>افزودن دسته</h2></header>{brands.length?<CategoryForm brands={brands}/>:<p className="admin-category-prerequisite">ابتدا یک برند ثبت کنید.</p>}</section>
 <section className="admin-brand-list"><header><h2>دسته‌های ثبت‌شده</h2><span>{categories.length}</span></header>{categories.length?categories.map(category=>{const fa=category.translations.find(t=>t.locale==="fa"),en=category.translations.find(t=>t.locale==="en"),brand=brands.find(item=>item.id===category.brand_id);return <details className="admin-brand-row admin-category-row" key={category.id}><summary><span className="admin-category-swatch" style={{background:category.accent_color}}/><div><strong>{fa?.name||category.code}</strong><small>{brand?.name} · <span dir="ltr">{en?.name||category.code}</span></small></div><i className={category.is_published?"published":""}>{category.is_published?"منتشرشده":"پیش‌نویس"}</i><b>ویرایش</b></summary><CategoryForm brands={brands} category={category}/>{profile.role!=="seo"?<form action={deleteCategory} className="admin-brand-delete"><input type="hidden" name="id" value={category.id}/><button>حذف دسته</button></form>:null}</details>}):<div className="admin-catalog-empty"><strong>هنوز دسته‌ای ثبت نشده است</strong></div>}</section>
 </main>;
}

function CategoryForm({brands,category}:{brands:Brand[];category?:Category}){const fa=category?.translations.find(t=>t.locale==="fa"),en=category?.translations.find(t=>t.locale==="en");return <form action={saveCategory} className="admin-catalog-form admin-category-form">{category?<input type="hidden" name="id" value={category.id}/>:null}<label><span>برند</span><select name="brand_id" required defaultValue={category?.brand_id}>{brands.map(brand=><option value={brand.id} key={brand.id}>{brand.name}</option>)}</select></label><label><span>کد دسته</span><input name="code" dir="ltr" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={category?.code}/></label><label><span>آیکن</span><select name="icon_key" defaultValue={category?.icon_key||"oil"}><option value="oil">روغن</option><option value="gear">دنده</option><option value="brake">ترمز</option><option value="coolant">خنک‌کننده</option><option value="fluid">سیالات</option><option value="package">عمومی</option></select></label><label><span>رنگ دسته</span><input name="accent_color" dir="ltr" type="color" defaultValue={category?.accent_color||"#164b82"}/></label><label><span>ترتیب نمایش</span><input name="position" type="number" min="0" defaultValue={category?.position??0}/></label>
 <LocaleFields locale="fa" values={fa}/><LocaleFields locale="en" values={en}/><label className="admin-publish-check"><input type="checkbox" name="is_published" defaultChecked={category?.is_published}/><span>نمایش در وب‌سایت</span></label><button>‌{category?"ذخیره تغییرات":"ثبت دسته"}</button></form>}
function LocaleFields({locale,values}:{locale:"fa"|"en";values?:Translation}){const fa=locale==="fa";return <fieldset dir={fa?"rtl":"ltr"}><legend>{fa?"فارسی":"English"}</legend><label><span>{fa?"نام دسته":"Category name"}</span><input name={`${locale}_name`} required defaultValue={values?.name}/></label><label><span>{fa?"نشانی":"Slug"}</span><input name={`${locale}_slug`} dir="ltr" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={values?.slug}/></label><label className="wide"><span>{fa?"توضیح کوتاه":"Short description"}</span><textarea name={`${locale}_description`} rows={3} defaultValue={values?.description??""}/></label><label><span>{fa?"عنوان سئو":"SEO title"}</span><input name={`${locale}_seo_title`} defaultValue={values?.seo_title??""}/></label><label><span>{fa?"توضیحات سئو":"SEO description"}</span><input name={`${locale}_seo_description`} defaultValue={values?.seo_description??""}/></label></fieldset>}
