import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { InternationalInquiryForm as InternationalForm } from "@/components/international-inquiry-form";
import { InnerPageHero } from "@/components/inner-page-hero";
import { isLocale } from "@/lib/i18n";

type Props = { params: Promise<{ lang: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { lang } = await params; if (!isLocale(lang)) return {}; const fa = lang === "fa"; return { title: fa ? "همکاری بین‌المللی | دیار صنعت تبریز" : "International cooperation | Diyar Sanat Tabriz", description: fa ? "ثبت پیشنهاد واردات، توزیع، نمایندگی منطقه‌ای یا همکاری تجاری بین‌المللی با دیار صنعت تبریز." : "Submit an import, distribution, regional representation, or international partnership inquiry to Diyar Sanat Tabriz.", alternates: { canonical: `/${lang}/international-cooperation`, languages: { fa: "/fa/international-cooperation", en: "/en/international-cooperation" } } }; }
export default async function InternationalPage({ params }: Props) { const { lang } = await params; if (!isLocale(lang)) notFound(); const fa = lang === "fa"; return <main id="main-content" className="business-page"><InnerPageHero locale={lang} current={fa ? "همکاری بین‌المللی" : "International cooperation"} eyebrow={fa ? "در مسیر بازارهای منطقه‌ای و جهانی" : "Toward regional and global markets"} title={fa ? "همکاری بین‌المللی" : "International cooperation"} description={fa ? "دیار صنعت در مسیر توسعه بازارهای آینده، پیشنهادهای حرفه‌ای واردکنندگان، توزیع‌کنندگان و شرکای صنعتی را بررسی می‌کند؛ این صفحه به معنی ادعای صادرات فعال نیست." : "As it develops future markets, Diyar Sanat welcomes professional inquiries from importers, distributors, and industrial partners; this does not claim active exports."} /><div className="container-wide international-intro"><article><span>01</span><h2>{fa ? "شناخت بازار" : "Market understanding"}</h2><p>{fa ? "کشور، شبکه توزیع و نیازهای بازار مقصد را معرفی کنید." : "Introduce the destination market, network, and demand."}</p></article><article><span>02</span><h2>{fa ? "انتخاب محصول" : "Product fit"}</h2><p>{fa ? "گروه محصول و حجم تقریبی موردنظر را مشخص کنید." : "Specify product groups and estimated volume."}</p></article><article><span>03</span><h2>{fa ? "مدل همکاری" : "Partnership model"}</h2><p>{fa ? "ساختار پیشنهادی همکاری برای ارزیابی اولیه ثبت می‌شود." : "Your proposed model is captured for initial evaluation."}</p></article></div><div className="container-wide single-form-wrap"><InternationalForm locale={lang} /></div></main>; }
