"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Method="password"|"sms";
export function AdminLoginForm({loginMethod,smsReady}:{loginMethod:"password"|"sms"|"both";smsReady:boolean}){const router=useRouter();const[method,setMethod]=useState<Method>(loginMethod==="sms"?"sms":"password");const[otpSent,setOtpSent]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const supabase=createClient();const allowPassword=loginMethod!=="sms";const allowSms=loginMethod!=="password";
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{if(method==="password"){const{error:authError}=await supabase.auth.signInWithPassword({email:String(form.get("email")),password:String(form.get("password"))});if(authError)throw authError;router.replace("/admin");router.refresh();return;}const rawPhone=String(form.get("phone")).replace(/\D/g,"");const phone=rawPhone.startsWith("0")?`+98${rawPhone.slice(1)}`:`+${rawPhone}`;if(!smsReady)throw new Error("ورود پیامکی هنوز از بخش تنظیمات و متغیرهای امن سرور تکمیل نشده است.");if(!otpSent){const{error:otpError}=await supabase.auth.signInWithOtp({phone,options:{shouldCreateUser:false}});if(otpError)throw otpError;setOtpSent(true);}else{const{error:verifyError}=await supabase.auth.verifyOtp({phone,token:String(form.get("otp")),type:"sms"});if(verifyError)throw verifyError;router.replace("/admin");router.refresh();}}catch(value){setError(value instanceof Error?value.message:"ورود انجام نشد.");}finally{setBusy(false)}}
  return <div className="admin-login-card"><header><h1>ورود پرسنل</h1></header>{loginMethod==="both"?<div className="admin-login-tabs" role="tablist"><button type="button" className={method==="password"?"active":""} onClick={()=>{setMethod("password");setError("")}}>رمز عبور</button><button type="button" className={method==="sms"?"active":""} onClick={()=>{setMethod("sms");setError("")}}>کد پیامکی</button></div>:null}<form onSubmit={submit}>{method==="password"&&allowPassword?<><label><span>ایمیل سازمانی</span><input required name="email" type="email" dir="ltr" autoComplete="username" placeholder="name@company.com"/></label><label><span>رمز عبور</span><input required name="password" type="password" dir="ltr" minLength={12} autoComplete="current-password"/></label></>:null}{method==="sms"&&allowSms?<><label><span>شماره موبایل</span><input required name="phone" type="tel" dir="ltr" inputMode="tel" pattern="09[0-9]{9}" placeholder="09xxxxxxxxx" autoComplete="tel"/></label>{otpSent?<label><span>کد یک‌بارمصرف</span><input required name="otp" dir="ltr" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code"/></label>:null}</>:null}<label className="admin-captcha"><span>پرسش امنیتی: حاصل ۳ + ۴</span><input required inputMode="numeric" pattern="7" placeholder="پاسخ"/></label>{error?<p className="admin-login-error" role="alert">{error}</p>:null}<button disabled={busy} type="submit">{busy?"در حال بررسی…":method==="sms"&&!otpSent?"ارسال کد ورود":"ورود به پنل"}</button></form></div>}
