"use client";
import { useEffect, useRef, useState } from "react";

type Option={id:number;name_fa:string;name_en:string};
async function load(url:string,signal?:AbortSignal){const response=await fetch(url,{signal,headers:{Accept:"application/json"}});if(!response.ok)throw new Error();return (await response.json() as {items:Option[]}).items;}

export function AdminCityPicker({name="city_id",required=true,initial}:{name?:string;required?:boolean;initial?:{id:number;countryId:number;provinceId:number;label:string}}){
 const[countries,setCountries]=useState<Option[]>([]),[provinces,setProvinces]=useState<Option[]>([]),[cities,setCities]=useState<Option[]>([]),[country,setCountry]=useState(initial?.countryId??0),[province,setProvince]=useState(initial?.provinceId??0),[city,setCity]=useState(initial?.id??0),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{load("/api/admin/locations?mode=countries").then(setCountries).catch(()=>setError("دریافت کشورها انجام نشد."))},[]);
 useEffect(()=>{if(!country)return;load(`/api/admin/locations?mode=provinces&country=${country}`).then(setProvinces).catch(()=>setError("دریافت استان‌ها انجام نشد."))},[country]);
 useEffect(()=>{if(!province)return;if(timer.current)clearTimeout(timer.current);const controller=new AbortController();timer.current=setTimeout(()=>{setBusy(true);load(`/api/admin/locations?mode=cities&province=${province}&q=${encodeURIComponent(query)}`,controller.signal).then(setCities).catch(error=>{if(error.name!=="AbortError")setError("جست‌وجوی شهر انجام نشد.")}).finally(()=>setBusy(false))},300);return()=>{controller.abort();if(timer.current)clearTimeout(timer.current)}},[province,query]);
 return <div className="admin-cascade-picker"><input type="hidden" name={name} value={city||""} required={required}/><div className="admin-cascade-grid"><label><span>کشور</span><select value={country} onChange={event=>{setCountry(Number(event.target.value));setProvinces([]);setProvince(0);setCities([]);setCity(0)}} required><option value="">انتخاب کشور</option>{countries.map(item=><option value={item.id} key={item.id}>{item.name_fa}</option>)}</select></label><label><span>استان</span><select value={province} onChange={event=>{setProvince(Number(event.target.value));setCities([]);setCity(0)}} disabled={!country||busy} required><option value="">انتخاب استان</option>{provinces.map(item=><option value={item.id} key={item.id}>{item.name_fa}</option>)}</select></label></div><label className="admin-city-search"><span>جست‌وجوی شهر</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} disabled={!province} placeholder={province?"حداقل دو حرف از نام شهر را وارد کنید":"ابتدا کشور و استان را انتخاب کنید"}/>{busy?<i>در حال جست‌وجو…</i>:null}</label>{province?<div className="admin-city-results" role="listbox" aria-label="نتایج شهرها">{initial&&city===initial.id&&!cities.some(item=>item.id===initial.id)?<button type="button" className="selected" onClick={()=>setCity(initial.id)}>{initial.label}</button>:null}{cities.map(item=><button type="button" role="option" aria-selected={city===item.id} className={city===item.id?"selected":""} onClick={()=>setCity(item.id)} key={item.id}><span>{item.name_fa}</span><small dir="ltr">{item.name_en}</small></button>)}{!busy&&!cities.length?<p>شهری با این عبارت پیدا نشد.</p>:null}</div>:null}{error?<small className="admin-picker-error" role="alert">{error}</small>:null}</div>
}

export function AdminCitySearch({provinceId}:{provinceId:number}){const[query,setQuery]=useState(""),[items,setItems]=useState<Option[]>([]),[busy,setBusy]=useState(false);useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setBusy(true);load(`/api/admin/locations?mode=cities&province=${provinceId}&q=${encodeURIComponent(query)}`,controller.signal).then(setItems).finally(()=>setBusy(false))},300);return()=>{clearTimeout(timer);controller.abort()}},[provinceId,query]);return <div className="admin-location-live-search"><label><span>جست‌وجوی شهر در استان انتخاب‌شده</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="نام فارسی یا انگلیسی شهر"/></label>{busy?<p>در حال جست‌وجو…</p>:<div>{items.map(item=><a href={`?province=${provinceId}&city=${item.id}`} key={item.id}><span>{item.name_fa}</span><small dir="ltr">{item.name_en}</small></a>)}</div>}</div>}
