"use client";
import Link from "next/link";
import { usePathname,useRouter } from "next/navigation";
import { useState } from "react";
import { BrandMark } from "@/components/brand-mark";
import { DashboardIcon,LogoutIcon,SettingsIcon,UsersIcon } from "@/components/admin-icons";
import { adminModules,roleLabel,type StaffRole } from "@/lib/admin/modules";
import { createClient } from "@/lib/supabase/client";

export function AdminShell({children,name,role,date,time}:{children:React.ReactNode;name:string;role:StaffRole;date:string;time:string}){const path=usePathname();const router=useRouter();const[menuOpen,setMenuOpen]=useState(false);const visible=adminModules.filter(item=>(item.roles as readonly string[]).includes(role));async function logout(){await createClient().auth.signOut();router.replace("/admin/login");router.refresh()}return <div className="admin-shell" dir="rtl"><aside className={menuOpen?"open":""}><header><BrandMark locale="fa" compact/><button type="button" onClick={()=>setMenuOpen(false)} aria-label="بستن منو">×</button></header><nav><Link className={path==="/admin"?"active":""} href="/admin" onClick={()=>setMenuOpen(false)}><DashboardIcon/>داشبورد</Link><small>مدیریت محتوا</small>{visible.map(item=>{const Icon=item.icon;return <Link className={path===`/admin/${item.key}`?"active":""} href={`/admin/${item.key}`} onClick={()=>setMenuOpen(false)} key={item.key}><Icon/>{item.fa}</Link>})}{role==="manager"?<><small>مدیریت سامانه</small><Link href="/admin/staff"><UsersIcon/>پرسنل و نقش‌ها</Link><Link href="/admin/settings"><SettingsIcon/>تنظیمات ورود</Link></>:null}</nav></aside>{menuOpen?<button className="admin-sidebar-backdrop" aria-label="بستن منو" onClick={()=>setMenuOpen(false)}/>:null}<div className="admin-workspace"><header className="admin-topbar"><button className="admin-menu-trigger" onClick={()=>setMenuOpen(true)} aria-label="باز کردن منو">☰</button><div className="admin-user-copy"><small>سامانه مدیریت دیار صنعت</small><strong>{name}</strong></div><div className="admin-jalali-clock"><span>{date}</span><time>{time}</time></div><span className="admin-role-chip">{roleLabel(role)}</span><button className="admin-logout" type="button" onClick={logout}><LogoutIcon/><span>خروج</span></button></header>{children}</div></div>}
