"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import type { Locale } from "@/lib/i18n";
type MediaKind="news"|"blog"|"tutorial";
type MediaArticle={slug:string;kind:MediaKind;title:string;excerpt:string;image:string;date:string;readingTime:number};
function mediaKindLabel(locale:Locale,kind:MediaKind){const labels={fa:{news:"اخبار",blog:"وبلاگ",tutorial:"آموزش"},en:{news:"News",blog:"Blog",tutorial:"Guide"}} as const;return labels[locale][kind]}
export function MediaArchive({locale,articles}:{locale:Locale;articles:MediaArticle[]}){const fa=locale==="fa";const [kind,setKind]=useState<"all"|MediaKind>("all");const [query,setQuery]=useState("");const filtered=articles.filter(item=>(kind==="all"||item.kind===kind)&&`${item.title} ${item.excerpt}`.toLocaleLowerCase(locale).includes(query.trim().toLocaleLowerCase(locale)));return <><div className="media-archive-tools"><div role="group" aria-label={fa?"نوع محتوا":"Content type"}>{(["all","news","blog","tutorial"] as const).map(item=><button type="button" key={item} className={kind===item?"active":undefined} onClick={()=>setKind(item)}>{item==="all"?(fa?"همه مطالب":"All content"):mediaKindLabel(locale,item)}</button>)}</div><label><span className="sr-only">{fa?"جست‌وجو در رسانه":"Search media"}</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={fa?"جست‌وجو در مطالب...":"Search articles..."}/></label></div><div className="media-archive-grid">{filtered.map((article,index)=><article key={article.slug} className={index===0&&kind==="all"&&!query?"media-archive-featured":undefined}><Link className="media-archive-image" href={`/${locale}/media/${article.slug}`}><Image src={article.image} alt="" fill sizes={index===0?"(max-width:800px) 100vw, 52vw":"(max-width:800px) 90vw, 320px"}/><span>{mediaKindLabel(locale,article.kind)}</span></Link><div className="media-archive-copy"><div><time dateTime={article.date}>{new Intl.DateTimeFormat(fa?"fa-IR":"en-US",{dateStyle:"medium"}).format(new Date(`${article.date}T12:00:00Z`))}</time><span>•</span><small>{article.readingTime} {fa?"دقیقه مطالعه":"min read"}</small></div><h2><Link href={`/${locale}/media/${article.slug}`}>{article.title}</Link></h2><p>{article.excerpt}</p><Link className="media-archive-action" href={`/${locale}/media/${article.slug}`}>{fa?"مطالعه مطلب":"Read article"}<b aria-hidden="true">←</b></Link></div></article>)}</div>{!filtered.length?<div className="media-archive-empty">{fa?"مطلبی با این فیلتر پیدا نشد.":"No article matches these filters."}</div>:null}</>}
