"use client";
import { useState } from "react";
import { AdminUploadField } from "@/components/admin-upload-field";
const icons=["shield","droplet","gear","snowflake","thermometer","flask","brake","oil","package","check","star","leaf"];
type Feature={icon_key:string;title_fa:string;title_en:string;description_fa?:string|null;description_en?:string|null};type Application={title_fa:string;title_en:string;description_fa?:string|null;description_en?:string|null};type Image={file_url:string;alt_fa:string;alt_en:string;is_primary:boolean};type Download={file_url:string;title_fa:string;title_en:string;file_type:string};
export function ProductContentBuilder({features:initialFeatures=[],applications:initialApplications=[],images:initialImages=[],downloads:initialDownloads=[]}:{features?:Feature[];applications?:Application[];images?:Image[];downloads?:Download[]}){const[features,setFeatures]=useState(initialFeatures),[applications,setApplications]=useState(initialApplications),[images,setImages]=useState(initialImages),[downloads,setDownloads]=useState(initialDownloads);return <div className="admin-product-builder wide">
 <Builder title="گالری تصاویر محصول" description="برای هر تصویر Alt فارسی و انگلیسی ثبت کنید." onAdd={()=>setImages(items=>[...items,{file_url:"",alt_fa:"",alt_en:"",is_primary:!items.length}])}>{images.map((item,index)=><article className="admin-builder-card" key={index}><header><strong>تصویر {index+1}</strong><button type="button" onClick={()=>setImages(items=>items.filter((_,i)=>i!==index))}>حذف</button></header><AdminUploadField name={`gallery_url_${index}`} label="فایل تصویر" folder="products/gallery" accept="image/jpeg,image/png,image/webp,image/avif" defaultValue={item.file_url}/><label><span>Alt فارسی</span><input name={`gallery_alt_fa_${index}`} required defaultValue={item.alt_fa}/></label><label dir="ltr"><span>English alt</span><input name={`gallery_alt_en_${index}`} required defaultValue={item.alt_en}/></label><label className="admin-publish-check"><input type="radio" name="gallery_primary" value={index} defaultChecked={item.is_primary}/><span>تصویر اصلی</span></label></article>)}<input type="hidden" name="gallery_count" value={images.length}/></Builder>
 <Builder title="ویژگی‌های آیکن‌دار" description="مزیت‌هایی مانند رویکرد محافظتی و عملکرد پایدار را تعریف کنید." onAdd={()=>setFeatures(items=>[...items,{icon_key:"shield",title_fa:"",title_en:""}])}>{features.map((item,index)=><article className="admin-builder-card" key={index}><header><strong>ویژگی {index+1}</strong><button type="button" onClick={()=>setFeatures(items=>items.filter((_,i)=>i!==index))}>حذف</button></header><label><span>آیکن SVG</span><select name={`feature_icon_${index}`} defaultValue={item.icon_key}>{icons.map(icon=><option key={icon}>{icon}</option>)}</select></label><label><span>عنوان فارسی</span><input name={`feature_title_fa_${index}`} required defaultValue={item.title_fa}/></label><label dir="ltr"><span>English title</span><input name={`feature_title_en_${index}`} required defaultValue={item.title_en}/></label><label><span>توضیح فارسی</span><textarea name={`feature_description_fa_${index}`} rows={2} defaultValue={item.description_fa??""}/></label><label dir="ltr"><span>English description</span><textarea name={`feature_description_en_${index}`} rows={2} defaultValue={item.description_en??""}/></label></article>)}<input type="hidden" name="feature_count" value={features.length}/></Builder>
 <Builder title="کاربردهای محصول" description="کاربردهای تخصصی محصول را به‌صورت دوزبانه اضافه کنید." onAdd={()=>setApplications(items=>[...items,{title_fa:"",title_en:""}])}>{applications.map((item,index)=><article className="admin-builder-card" key={index}><header><strong>کاربرد {index+1}</strong><button type="button" onClick={()=>setApplications(items=>items.filter((_,i)=>i!==index))}>حذف</button></header><label><span>عنوان فارسی</span><input name={`application_title_fa_${index}`} required defaultValue={item.title_fa}/></label><label dir="ltr"><span>English title</span><input name={`application_title_en_${index}`} required defaultValue={item.title_en}/></label><label><span>توضیح فارسی</span><textarea name={`application_description_fa_${index}`} rows={2} defaultValue={item.description_fa??""}/></label><label dir="ltr"><span>English description</span><textarea name={`application_description_en_${index}`} rows={2} defaultValue={item.description_en??""}/></label></article>)}<input type="hidden" name="application_count" value={applications.length}/></Builder>
 <Builder title="دانلودها و کاتالوگ محصول" description="کاتالوگ، دیتاشیت، راهنما یا گواهی را به همین محصول متصل کنید." onAdd={()=>setDownloads(items=>[...items,{file_url:"",title_fa:"",title_en:"",file_type:"catalog"}])}>{downloads.map((item,index)=><article className="admin-builder-card" key={index}><header><strong>فایل {index+1}</strong><button type="button" onClick={()=>setDownloads(items=>items.filter((_,i)=>i!==index))}>حذف</button></header><AdminUploadField name={`download_url_${index}`} label="فایل" folder="products/downloads" accept="application/pdf" defaultValue={item.file_url}/><label><span>نوع فایل</span><select name={`download_type_${index}`} defaultValue={item.file_type}><option value="catalog">کاتالوگ</option><option value="datasheet">دیتاشیت</option><option value="certificate">گواهی</option><option value="manual">راهنما</option><option value="other">سایر</option></select></label><label><span>عنوان فارسی</span><input name={`download_title_fa_${index}`} required defaultValue={item.title_fa}/></label><label dir="ltr"><span>English title</span><input name={`download_title_en_${index}`} required defaultValue={item.title_en}/></label></article>)}<input type="hidden" name="download_count" value={downloads.length}/></Builder>
 </div>}
function Builder({title,description,onAdd,children}:{title:string;description:string;onAdd:()=>void;children:React.ReactNode}){return <section className="admin-builder-section"><header><div><h3>{title}</h3><p>{description}</p></div><button type="button" onClick={onAdd}>+ افزودن</button></header><div>{children}</div></section>}
