"use client";
import {useState} from "react";import type {Locale} from "@/lib/i18n";
type Item={title:string;description:string};type Spec={label:string;value:string};type Download={title:string;url:string;type:string};
export function ProductDetailTabs({locale,description,category,applications=[],features=[],specifications=[],downloads=[]}:{locale:Locale;description:string;category:string;applications?:Item[];features?:Item[];specifications?:Spec[];downloads?:Download[]}){const fa=locale==="fa",[tab,setTab]=useState("description"),tabs=[{id:"description",label:fa?"توضیحات محصول":"Description"},{id:"applications",label:fa?"کاربردها":"Applications"},{id:"features",label:fa?"ویژگی‌ها":"Features"},{id:"technical",label:fa?"مشخصات فنی":"Technical data"},{id:"downloads",label:fa?"دانلودها":"Downloads"}];return <section className="product-tabs"><div className="product-tab-list" role="tablist" aria-label={fa?"اطلاعات محصول":"Product information"}>{tabs.map(item=><button key={item.id} type="button" role="tab" aria-selected={tab===item.id} onClick={()=>setTab(item.id)}>{item.label}</button>)}</div><div className="product-tab-panel" role="tabpanel">
{tab==="description"?<><h2>{fa?"معرفی محصول":"Product overview"}</h2><p>{description}</p></>:null}
{tab==="applications"?<><h2>{fa?"کاربردهای محصول":"Product applications"}</h2>{applications.length?<div className="product-managed-list">{applications.map(item=><article key={item.title}><h3>{item.title}</h3>{item.description?<p>{item.description}</p>:null}</article>)}</div>:<p>{fa?`کاربرد تأییدشده‌ای برای گروه ${category} ثبت نشده است.`:`No approved application has been entered for ${category}.`}</p>}</>:null}
{tab==="features"?<><h2>{fa?"ویژگی‌های محصول":"Product features"}</h2>{features.length?<div className="product-managed-list">{features.map(item=><article key={item.title}><h3>{item.title}</h3>{item.description?<p>{item.description}</p>:null}</article>)}</div>:<p>{fa?"ویژگی تأییدشده‌ای ثبت نشده است.":"No approved feature has been entered."}</p>}</>:null}
{tab==="technical"?<><h2>{fa?"مشخصات فنی":"Technical data"}</h2>{specifications.length?<dl className="product-managed-specs">{specifications.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl>:<p>{fa?"مشخصات فنی هنوز ثبت نشده است.":"Technical specifications have not been entered yet."}</p>}</>:null}
{tab==="downloads"?<>{downloads.length?<div className="product-managed-downloads">{downloads.map(item=><a href={item.url} target="_blank" rel="noreferrer" key={item.url}><span>↓</span><div><strong>{item.title}</strong><small>{item.type}</small></div></a>)}</div>:<div className="product-download-empty"><span>↓</span><h2>{fa?"فایل تأییدشده‌ای منتشر نشده است":"No approved file is published"}</h2></div>}</>:null}
</div></section>}
