"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { SearchIcon } from "@/components/icons";
import type { Locale } from "@/lib/i18n";

export function SiteSearch({ locale }: { locale: Locale }) {
  const fa = locale === "fa"; const [open,setOpen]=useState(false); const [query,setQuery]=useState(""); const inputRef=useRef<HTMLInputElement>(null);
  const items = fa ? [["محصولات","آرشیو روغن موتور، واسکازین، روغن ترمز و ضدیخ","products"],["روغن موتور پیشرفته 10W-40","صفحه مشخصات و معرفی محصول","products/advanced-engine-oil-10w40"],["نمایندگان","یافتن نماینده در ایران و عراق","representatives"],["درباره ما","شرکت، کارخانه، تحقیق و توسعه و کنترل کیفیت","about"],["تماس با ما","اطلاعات تماس و ارسال پیام","contact"],["فرصت‌های شغلی","موقعیت‌ها و ارسال رزومه","careers"],["همکاری بین‌المللی","فرم پیشنهاد همکاری تجاری","international-cooperation"]] : [["Products","Engine oil, gear oil, brake fluid, and antifreeze archive","products"],["Advanced engine oil 10W-40","Product overview and specifications","products/advanced-engine-oil-10w40"],["Representatives","Find representatives in Iran and Iraq","representatives"],["About us","Company, factory, R&D, and quality control","about"],["Contact","Contact details and inquiry form","contact"],["Careers","Open roles and résumé submission","careers"],["International cooperation","Business partnership inquiry","international-cooperation"]];
  const normalized=query.trim().toLocaleLowerCase(locale); const results=normalized ? items.filter(item=>`${item[0]} ${item[1]}`.toLocaleLowerCase(locale).includes(normalized)) : items.slice(0,5);
  useEffect(()=>{if(!open)return; inputRef.current?.focus(); const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)}; document.addEventListener("keydown",close); return()=>document.removeEventListener("keydown",close)},[open]);
  return <><button className="icon-button desktop-tool" type="button" aria-label={fa?"جست‌وجو":"Search"} aria-expanded={open} onClick={()=>setOpen(true)}><SearchIcon className="size-5"/></button>{open?<div className="site-search-overlay" role="dialog" aria-modal="true" aria-label={fa?"جست‌وجوی سایت":"Site search"} onMouseDown={(event)=>{if(event.target===event.currentTarget)setOpen(false)}}><div className="site-search-panel"><header><div><span>{fa?"جست‌وجوی سریع":"Quick search"}</span><h2>{fa?"دنبال چه چیزی هستید؟":"What are you looking for?"}</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label={fa?"بستن":"Close"}>×</button></header><label className="site-search-input"><SearchIcon className="size-5"/><input ref={inputRef} type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={fa?"نام محصول، نماینده یا صفحه...":"Product, representative, or page..."}/><kbd>ESC</kbd></label><div className="site-search-results"><small>{query?(fa?`${results.length} نتیجه`:`${results.length} results`):(fa?"دسترسی‌های پیشنهادی":"Suggested destinations")}</small>{results.length?results.map(([title,description,path])=><Link key={path} href={`/${locale}/${path}`} onClick={()=>setOpen(false)}><span><SearchIcon className="size-4"/></span><div><strong>{title}</strong><small>{description}</small></div><b aria-hidden="true">←</b></Link>):<div className="site-search-empty">{fa?"نتیجه‌ای پیدا نشد؛ عبارت کوتاه‌تری امتحان کنید.":"No results found. Try a shorter phrase."}</div>}</div></div></div>:null}</>;
}
