import { AdminUploadField } from "@/components/admin-upload-field";
import { requireStaff } from "@/lib/admin/auth";
import { createClient } from "@/lib/supabase/server";
import { createAsset, deleteAsset } from "../library-actions";

type Asset = { id:number; asset_type:"image"|"video"|"document"|"catalog"; title_fa:string; title_en:string; description_fa:string|null; description_en:string|null; file_url:string; thumbnail_url:string|null; is_public:boolean; downloadable:boolean };

export default async function MediaLibraryPage() {
  const { profile } = await requireStaff();
  const { data: rows } = await (await createClient()).from("media_assets").select("id,asset_type,title_fa,title_en,description_fa,description_en,file_url,thumbnail_url,is_public,downloadable").order("created_at", { ascending:false });
  const data = rows ?? [];
  return <main className="admin-module-page"><header><div><div><small>مدیریت دارایی‌ها</small><h1>رسانه و فایل‌ها</h1><p>مرجع مرکزی تصاویر، ویدیوها و اسناد</p></div></div></header><section className="admin-brand-create"><header><h2>افزودن فایل</h2></header><AssetForm /></section><section className="admin-card-section"><header><div><small>کتابخانه</small><h2>فایل‌های ثبت‌شده</h2></div><span>{data.length}</span></header><div className="admin-entity-grid">{data.map(item => <article className="admin-entity-card" key={item.id}><div className="admin-entity-media">{item.thumbnail_url ? <img src={item.thumbnail_url} alt={item.title_fa} /> : item.asset_type === "image" ? <img src={item.file_url} alt={item.title_fa} /> : <span>{item.asset_type === "video" ? "▶" : "DOC"}</span>}<i className={item.is_public ? "published" : ""}>{item.is_public ? "عمومی" : "داخلی"}</i></div><div className="admin-entity-body"><small>{assetLabel(item.asset_type)}</small><h3>{item.title_fa}</h3><p dir="ltr">{item.title_en}</p></div><div className="admin-entity-actions"><details className="admin-card-editor"><summary>ویرایش</summary><div className="admin-card-editor-panel"><AssetForm item={item} /></div></details>{profile.role !== "seo" ? <form action={deleteAsset}><input type="hidden" name="id" value={item.id} /><button className="danger">حذف</button></form> : null}</div></article>)}</div></section></main>;
}

function assetLabel(value:Asset["asset_type"]){return {image:"تصویر",video:"ویدیو",document:"سند",catalog:"کاتالوگ"}[value]}
function AssetForm({item}:{item?:Asset}){return <form action={createAsset} className="admin-catalog-form">{item?<input type="hidden" name="id" value={item.id}/>:null}<label><span>نوع فایل</span><select name="asset_type" defaultValue={item?.asset_type}><option value="image">تصویر</option><option value="video">ویدیو</option><option value="document">سند</option><option value="catalog">کاتالوگ</option></select></label><label><span>عنوان فارسی</span><input name="title_fa" required defaultValue={item?.title_fa}/></label><label><span>عنوان انگلیسی</span><input name="title_en" dir="ltr" required defaultValue={item?.title_en}/></label><AdminUploadField name="file_url" label="فایل اصلی" folder="media-library" accept="image/jpeg,image/png,image/webp,image/avif,application/pdf,video/mp4,video/webm" defaultValue={item?.file_url??""}/><AdminUploadField name="thumbnail_url" label="تصویر بندانگشتی" folder="media-thumbnails" accept="image/jpeg,image/png,image/webp" defaultValue={item?.thumbnail_url??""}/><label className="admin-publish-check"><input name="is_public" type="checkbox" defaultChecked={item?.is_public}/><span>قابل نمایش عمومی</span></label><label className="admin-publish-check"><input name="downloadable" type="checkbox" defaultChecked={item?.downloadable}/><span>قابل دانلود</span></label><button>{item?"ذخیره تغییرات":"ثبت فایل"}</button></form>}
