import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ResumeForm } from "@/components/inquiry-forms";
import { isLocale } from "@/lib/i18n";

type Props = { params: Promise<{ lang: string; slug: string }> };
export function generateStaticParams() { return [{ lang: "fa", slug: "general-application" }, { lang: "en", slug: "general-application" }]; }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { lang, slug } = await params; if (!isLocale(lang) || slug !== "general-application") return {}; const fa = lang === "fa"; return { title: fa ? "ارسال رزومه عمومی | دیار صنعت تبریز" : "General résumé submission | Diyar Sanat Tabriz", description: fa ? "معرفی تخصص و ارسال رزومه برای فرصت‌های شغلی آینده دیار صنعت تبریز." : "Introduce your expertise and submit a résumé for future Diyar Sanat opportunities.", alternates: { canonical: `/${lang}/careers/general-application` } }; }
export default async function CareerDetailPage({ params }: Props) { const { lang, slug } = await params; if (!isLocale(lang) || slug !== "general-application") notFound(); const fa = lang === "fa"; return <main id="main-content" className="career-detail-page"><div className="container-wide career-detail-head"><nav><Link href={`/${lang}`}>{fa ? "خانه" : "Home"}</Link><span>/</span><Link href={`/${lang}/careers`}>{fa ? "فرصت‌های شغلی" : "Careers"}</Link><span>/</span><span>{fa ? "رزومه عمومی" : "General résumé"}</span></nav><span className="career-status">{fa ? "همیشه در دسترس" : "Always available"}</span><h1>{fa ? "ارسال رزومه عمومی" : "General résumé submission"}</h1><p>{fa ? "این مسیر یک آگهی استخدام فعال نیست؛ برای معرفی تخصص شما و بررسی در فرصت‌های آینده طراحی شده است." : "This is not an active vacancy. It is a channel to introduce your expertise for future opportunities."}</p></div><div className="container-wide career-detail-grid"><aside><h2>{fa ? "فرایند بررسی" : "Review process"}</h2><ul><li>{fa ? "دریافت رزومه و دسته‌بندی تخصص" : "Résumé intake and expertise classification"}</li><li>{fa ? "تطبیق با نیازهای تأییدشده آینده" : "Matching against approved future needs"}</li><li>{fa ? "تماس فقط در صورت وجود موقعیت مرتبط" : "Contact only when a relevant role exists"}</li></ul><p>{fa ? "ارسال رزومه تضمین‌کننده دعوت به مصاحبه یا استخدام نیست." : "Submitting a résumé does not guarantee an interview or employment."}</p></aside><ResumeForm locale={lang} position="general-application" /></div></main>; }
