import { AdminUploadField } from "@/components/admin-upload-field";
import { requireStaff } from "@/lib/admin/auth";
import { createClient } from "@/lib/supabase/server";
import { createAlbum, createGalleryItem, deleteAlbum, deleteGalleryItem } from "../library-actions";

type Album={id:number;slug:string;title_fa:string;title_en:string;description_fa:string|null;description_en:string|null;cover_url:string|null;position:number;is_published:boolean};
type GalleryItem={id:number;album_id:number;media_type:"image"|"video";file_url:string;alt_fa:string;alt_en:string;caption_fa:string|null;caption_en:string|null;position:number;is_published:boolean};

export default async function GalleriesPage(){
  const {profile}=await requireStaff();const db=await createClient();
  const [albumResult,itemResult]=await Promise.all([db.from("gallery_albums").select("id,slug,title_fa,title_en,description_fa,description_en,cover_url,position,is_published").order("position"),db.from("gallery_items").select("id,album_id,media_type,file_url,alt_fa,alt_en,caption_fa,caption_en,position,is_published").order("position")]);
  const albums=albumResult.data??[],items=itemResult.data??[];
  return <main className="admin-module-page"><header><div><div><small>تصاویر مجموعه</small><h1>آلبوم‌های گالری</h1><p>مدیریت آلبوم‌ها، تصاویر و ویدیوها</p></div></div></header>
    <section className="admin-library-grid"><article><h2>آلبوم جدید</h2><AlbumForm/></article><article><h2>افزودن رسانه به آلبوم</h2>{albums.length?<GalleryItemForm albums={albums}/>:<p>ابتدا آلبوم بسازید.</p>}</article></section>
    <CardSection label="آرشیو تصویری" title="آلبوم‌های ثبت‌شده" count={albums.length}>{albums.map(album=><article className="admin-entity-card admin-gallery-card" key={album.id}><Media url={album.cover_url} alt={album.title_fa} status={album.is_published}/><div className="admin-entity-body"><small>{items.filter(item=>item.album_id===album.id).length} رسانه</small><h3>{album.title_fa}</h3><p dir="ltr">{album.title_en}</p></div><Actions id={album.id} canDelete={profile.role!=="seo"} deleteAction={deleteAlbum}><AlbumForm item={album}/></Actions></article>)}</CardSection>
    <CardSection label="محتوای آلبوم‌ها" title="رسانه‌های گالری" count={items.length}>{items.map(item=><article className="admin-entity-card" key={item.id}><Media url={item.media_type==="image"?item.file_url:null} alt={item.alt_fa} status={item.is_published}/><div className="admin-entity-body"><small>{albums.find(album=>album.id===item.album_id)?.title_fa??"آلبوم"}</small><h3>{item.alt_fa}</h3><p dir="ltr">{item.alt_en}</p></div><Actions id={item.id} canDelete={profile.role!=="seo"} deleteAction={deleteGalleryItem}><GalleryItemForm albums={albums} item={item}/></Actions></article>)}</CardSection>
  </main>;
}

function CardSection({label,title,count,children}:{label:string;title:string;count:number;children:React.ReactNode}){return <section className="admin-card-section"><header><div><small>{label}</small><h2>{title}</h2></div><span>{count}</span></header><div className="admin-entity-grid">{children}</div></section>}
function Media({url,alt,status}:{url:string|null;alt:string;status:boolean}){return <div className="admin-entity-media">{url?<img src={url} alt={alt}/>:<span>▧</span>}<i className={status?"published":""}>{status?"منتشرشده":"پیش‌نویس"}</i></div>}
function Actions({id,canDelete,deleteAction,children}:{id:number;canDelete:boolean;deleteAction:(data:FormData)=>Promise<void>;children:React.ReactNode}){return <div className="admin-entity-actions"><details className="admin-card-editor"><summary>ویرایش</summary><div className="admin-card-editor-panel">{children}</div></details>{canDelete?<form action={deleteAction}><input type="hidden" name="id" value={id}/><button className="danger">حذف</button></form>:null}</div>}
function AlbumForm({item}:{item?:Album}){return <form action={createAlbum} className="admin-catalog-form">{item?<input type="hidden" name="id" value={item.id}/>:null}<label><span>عنوان فارسی</span><input name="title_fa" required defaultValue={item?.title_fa}/></label><label><span>عنوان انگلیسی</span><input name="title_en" dir="ltr" required defaultValue={item?.title_en}/></label><label><span>Slug</span><input name="slug" dir="ltr" required defaultValue={item?.slug}/></label><AdminUploadField name="cover_url" label="کاور آلبوم" folder="gallery-covers" accept="image/jpeg,image/png,image/webp" defaultValue={item?.cover_url??""}/><label><span>ترتیب</span><input name="position" type="number" min="0" defaultValue={item?.position??0}/></label><label className="admin-publish-check"><input name="is_published" type="checkbox" defaultChecked={item?.is_published}/><span>انتشار</span></label><button>{item?"ذخیره تغییرات":"ثبت آلبوم"}</button></form>}
function GalleryItemForm({albums,item}:{albums:Album[];item?:GalleryItem}){return <form action={createGalleryItem} className="admin-catalog-form">{item?<input type="hidden" name="id" value={item.id}/>:null}<label><span>آلبوم</span><select name="album_id" defaultValue={item?.album_id}>{albums.map(album=><option key={album.id} value={album.id}>{album.title_fa}</option>)}</select></label><label><span>نوع</span><select name="media_type" defaultValue={item?.media_type}><option value="image">تصویر</option><option value="video">ویدیو</option></select></label><AdminUploadField name="file_url" label="فایل رسانه" folder="gallery" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" defaultValue={item?.file_url??""}/><label><span>متن جایگزین فارسی</span><input name="alt_fa" required defaultValue={item?.alt_fa}/></label><label><span>Alt text</span><input name="alt_en" dir="ltr" required defaultValue={item?.alt_en}/></label><label><span>ترتیب</span><input name="position" type="number" min="0" defaultValue={item?.position??0}/></label><label className="admin-publish-check"><input name="is_published" type="checkbox" defaultChecked={item?.is_published}/><span>انتشار</span></label><button>{item?"ذخیره تغییرات":"افزودن رسانه"}</button></form>}
