import { AdminCityPicker } from "@/components/admin-location-picker";
import { requireStaff } from "@/lib/admin/auth";
import { createClient } from "@/lib/supabase/server";
import { deleteRepresentative, saveRepresentative } from "./actions";

type Props={searchParams:Promise<{error?:string;saved?:string;deleted?:string}>};
type Rep={id:number;city_id:number;slug:string;business_name_fa:string;business_name_en:string|null;manager_name_fa:string;manager_name_en:string|null;address_fa:string;address_en:string|null;phone:string;whatsapp:string|null;latitude:number|null;longitude:number|null;directions_url:string|null;position:number;is_published:boolean};
type SelectedCity={id:number;province_id:number;name_fa:string;province:{id:number;country_id:number;name_fa:string};country:{id:number;name_fa:string}};

export default async function RepresentativesPage({searchParams}:Props){
 const[,query]=await Promise.all([requireStaff(),searchParams]);const db=await createClient();
 const{data:reps=[]}=await db.from("representatives").select("id,city_id,slug,business_name_fa,business_name_en,manager_name_fa,manager_name_en,address_fa,address_en,phone,whatsapp,latitude,longitude,directions_url,position,is_published").order("position");
 const cityIds=[...new Set((reps??[]).map(item=>item.city_id))];const{data:cities=[]}=cityIds.length?await db.from("cities").select("id,province_id,name_fa").in("id",cityIds):{data:[]};const provinceIds=[...new Set((cities??[]).map(item=>item.province_id))];const{data:provinces=[]}=provinceIds.length?await db.from("provinces").select("id,country_id,name_fa").in("id",provinceIds):{data:[]};const countryIds=[...new Set((provinces??[]).map(item=>item.country_id))];const{data:countries=[]}=countryIds.length?await db.from("countries").select("id,name_fa").in("id",countryIds):{data:[]};
 const selectedCities:SelectedCity[]=(cities??[]).map(city=>{const province=provinces?.find(item=>item.id===city.province_id);return{id:city.id,province_id:city.province_id,name_fa:city.name_fa,province:{id:province?.id??0,country_id:province?.country_id??0,name_fa:province?.name_fa??"—"},country:{id:province?.country_id??0,name_fa:countries?.find(item=>item.id===province?.country_id)?.name_fa??"—"}}});
 return <main className="admin-module-page admin-representatives-page"><header><div><div><small>شبکه فروش</small><h1>نمایندگان</h1><p>اطلاعات تماس و موقعیت نمایندگان</p></div></div></header>{query.error?<p className="admin-alert error">{query.error}</p>:null}{query.saved?<p className="admin-alert success">نماینده ذخیره شد.</p>:null}{query.deleted?<p className="admin-alert success">نماینده حذف شد.</p>:null}<section className="admin-brand-create"><header><h2>افزودن نماینده</h2></header><RepresentativeForm/></section><section className="admin-brand-list"><header><h2>نمایندگان ثبت‌شده</h2><span>{reps?.length??0}</span></header>{reps?.map(rep=>{const city=selectedCities.find(item=>item.id===rep.city_id);return <details className="admin-brand-row admin-representative-row" key={rep.id}><summary><span className="admin-rep-pin">⌖</span><div><strong>{rep.business_name_fa}</strong><small>{city?.name_fa??"—"} · <span dir="ltr">{rep.phone}</span></small></div><i className={rep.is_published?"published":""}>{rep.is_published?"منتشرشده":"پیش‌نویس"}</i><b>ویرایش</b></summary><RepresentativeForm rep={rep} selectedCity={city}/><form action={deleteRepresentative} className="admin-brand-delete"><input type="hidden" name="id" value={rep.id}/><button>حذف نماینده</button></form></details>})}</section></main>;
}

function RepresentativeForm({rep,selectedCity}:{rep?:Rep;selectedCity?:SelectedCity}){return <form action={saveRepresentative} className="admin-catalog-form admin-representative-form">{rep?<input type="hidden" name="id" value={rep.id}/>:null}<div className="wide"><AdminCityPicker initial={selectedCity?{id:selectedCity.id,provinceId:selectedCity.province.id,countryId:selectedCity.country.id,label:`${selectedCity.country.name_fa} / ${selectedCity.province.name_fa} / ${selectedCity.name_fa}`}:undefined}/></div><label><span>نشانی صفحه</span><input name="slug" dir="ltr" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={rep?.slug}/></label><label><span>ترتیب</span><input name="position" type="number" min="0" defaultValue={rep?.position??0}/></label><fieldset><legend>اطلاعات فارسی</legend><label><span>نام مجموعه</span><input name="business_name_fa" required defaultValue={rep?.business_name_fa}/></label><label><span>نام مسئول</span><input name="manager_name_fa" required defaultValue={rep?.manager_name_fa}/></label><label className="wide"><span>آدرس</span><textarea name="address_fa" required rows={3} defaultValue={rep?.address_fa}/></label></fieldset><fieldset dir="ltr"><legend>English information</legend><label><span>Business name</span><input name="business_name_en" defaultValue={rep?.business_name_en??""}/></label><label><span>Manager</span><input name="manager_name_en" defaultValue={rep?.manager_name_en??""}/></label><label className="wide"><span>Address</span><textarea name="address_en" rows={3} defaultValue={rep?.address_en??""}/></label></fieldset><label><span>تلفن</span><input name="phone" dir="ltr" required placeholder="+9841..." defaultValue={rep?.phone}/></label><label><span>واتساپ</span><input name="whatsapp" dir="ltr" placeholder="+989..." defaultValue={rep?.whatsapp??""}/></label><label><span>عرض جغرافیایی</span><input name="latitude" dir="ltr" type="number" min="-90" max="90" step="0.000001" defaultValue={rep?.latitude??""}/></label><label><span>طول جغرافیایی</span><input name="longitude" dir="ltr" type="number" min="-180" max="180" step="0.000001" defaultValue={rep?.longitude??""}/></label><label className="wide"><span>لینک مسیریابی</span><input name="directions_url" dir="ltr" type="url" placeholder="https://" defaultValue={rep?.directions_url??""}/></label><label className="admin-publish-check"><input type="checkbox" name="is_published" defaultChecked={rep?.is_published}/><span>نمایش در وب‌سایت</span></label><button>{rep?"ذخیره تغییرات":"ثبت نماینده"}</button></form>}
