create table public.faq_items(
  id bigint generated always as identity primary key,
  category_fa text not null,category_en text not null,
  question_fa text not null,question_en text not null,
  answer_fa text not null,answer_en text not null,
  position integer not null default 0 check(position>=0),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index faq_items_public_position_idx on public.faq_items(position) where is_published;
create trigger faq_items_set_updated_at before update on public.faq_items for each row execute function private.set_updated_at();
alter table public.faq_items enable row level security;
create policy faq_items_public_read on public.faq_items for select to anon,authenticated using(is_published);
create policy faq_items_staff_manage on public.faq_items for all to authenticated using((select private.has_staff_role(array['manager','admin','seo']))) with check((select private.has_staff_role(array['manager','admin','seo'])));
grant select on public.faq_items to anon,authenticated;grant insert,update,delete on public.faq_items to authenticated;grant usage,select on sequence public.faq_items_id_seq to authenticated;

with copy(namespace,key,fa,en,description) as (values
('home','hero.kicker','از تبریز','From Tabriz','تیتر اول هیرو'),('home','hero.title','تا بازارهای جهانی','Toward global markets','تیتر اصلی هیرو'),('home','hero.subtitle','ساخت ایران، حرکت به جلو','Made in Iran, moving forward','زیرعنوان هیرو'),('home','hero.description','تولیدکننده انواع روغن موتور، ضدیخ، روغن ترمز و واسکازین با نگاه رو به آینده','Automotive lubricants and specialty fluids built with a forward-looking approach','توضیح هیرو'),('home','hero.badge_title','ساخت ایران','Made in Iran','برچسب تصویر'),('home','hero.badge_subtitle','حرکت به جلو','Moving forward','برچسب تصویر'),('home','products.eyebrow','محصولات ما','Our products','عنوان کوچک محصولات'),('home','products.title','راهکارهای تخصصی برای عملکرد بهتر','Specialist solutions for better performance','عنوان محصولات'),('home','factory.eyebrow','درباره مجموعه','Inside the company','عنوان کوچک کارخانه'),('home','factory.title','دیار صنعت تبریز','Diyar Sanat Tabriz','عنوان کارخانه'),('home','factory.description','دیار صنعت با تمرکز بر توسعه روانکارها و سیالات تخصصی خودرو، مسیر تولید دقیق و رشد پایدار را دنبال می‌کند.','Diyar Sanat develops automotive lubricants and specialty fluids through disciplined production and sustainable growth.','متن معرفی کارخانه'),
('about','hero.current','درباره ما','About us','مسیر صفحه'),('about','hero.eyebrow','ساخت ایران، حرکت به جلو','Made in Iran, moving forward','عنوان کوچک'),('about','hero.title','دیار صنعت تبریز','Diyar Sanat Tabriz','عنوان اصلی'),('about','hero.description','معرفی شرکت، مسیر تولید و نگاه رو به آینده؛ دقیق، مستند و بدون ادعاهای تأییدنشده.','The company, its production direction, and forward-looking approach—presented precisely and without unverified claims.','توضیح هیرو'),('about','story.eyebrow','روایت مجموعه','Our story','عنوان کوچک معرفی'),('about','story.title','تولید تخصصی با نگاه مهندسی','Specialist production with an engineering mindset','عنوان معرفی'),('about','story.description','دیار صنعت تبریز در مسیر توسعه محصولات خودرویی قابل‌اعتماد، ایجاد فرایندهای منظم و ساختن ارتباط حرفه‌ای با بازار حرکت می‌کند.','Diyar Sanat Tabriz is developing dependable automotive products, disciplined processes, and professional market relationships.','متن معرفی'),('about','vision.title','حرکت مرحله‌به‌مرحله به سوی بازارهای منطقه‌ای و جهانی','A measured path toward regional and global markets','عنوان چشم‌انداز'),('about','vision.description','چشم‌انداز مجموعه، توسعه توانمندی محصول و همکاری‌های آینده است و به معنی ادعای صادرات فعال نیست.','The vision is to develop product capabilities and future partnerships and does not claim active exports.','متن چشم‌انداز'),
('contact','hero.current','تماس با ما','Contact','مسیر صفحه'),('contact','hero.eyebrow','ارتباط مستقیم','Direct communication','عنوان کوچک'),('contact','hero.title','با دیار صنعت در ارتباط باشید','Contact Diyar Sanat','عنوان اصلی'),('contact','hero.description','اطلاعات تماس مجموعه و مسیر ارتباط با واحدهای تخصصی را در این صفحه مشاهده کنید.','Find company contact information and reach the appropriate specialist team.','توضیح'),('contact','office.title','دفتر دیار صنعت تبریز','Diyar Sanat Tabriz office','عنوان اطلاعات تماس'),('contact','office.email','info@diyarsanat.com','info@diyarsanat.com','ایمیل'),('contact','office.phone','در انتظار تأیید رسمی','Pending official verification','تلفن'),('contact','office.address','تبریز، ایران — نشانی دقیق در انتظار تأیید','Tabriz, Iran — full address pending verification','نشانی'),
('faq','hero.current','پرسش‌های متداول','FAQ','مسیر صفحه'),('faq','hero.eyebrow','مرکز پاسخ‌گویی','Help center','عنوان کوچک'),('faq','hero.title','پاسخ سؤال‌های مهم، پیش از انتخاب','Answers before you choose','عنوان اصلی'),('faq','hero.description','درباره خرید از نمایندگان، اصالت کالا، انتخاب محصول و پیگیری درخواست پاسخ‌های روشن پیدا کنید.','Clear guidance on verified purchasing, authenticity, product choice, and tracking.','توضیح'),
('buying-guide','hero.current','راهنمای خرید','Buying guide','مسیر صفحه'),('buying-guide','hero.eyebrow','انتخاب مطمئن','Confident selection','عنوان کوچک'),('buying-guide','hero.title','درست انتخاب کنید، از مسیر معتبر تهیه کنید','Choose correctly. Buy through verified channels.','عنوان اصلی'),('buying-guide','hero.description','این وب‌سایت فروشگاه آنلاین نیست. محصولات را از نمایندگان معتبر تهیه کنید و نیاز فنی خودرو را بررسی کنید.','This website is not an online store. Buy from verified representatives and check vehicle requirements.','توضیح'),
('international','hero.current','همکاری بین‌المللی','International cooperation','مسیر صفحه'),('international','hero.eyebrow','در مسیر بازارهای منطقه‌ای و جهانی','Toward regional and global markets','عنوان کوچک'),('international','hero.title','همکاری بین‌المللی','International cooperation','عنوان اصلی'),('international','hero.description','دیار صنعت پیشنهادهای حرفه‌ای واردکنندگان، توزیع‌کنندگان و شرکای صنعتی را بررسی می‌کند؛ این صفحه به معنی ادعای صادرات فعال نیست.','Diyar Sanat welcomes professional inquiries from importers, distributors, and industrial partners; this does not claim active exports.','توضیح'),
('global-footer','credentials.title','نمادها و مجوزها','Credentials','عنوان مجوزها'),('global-footer','contact.title','اطلاعات تماس','Contact information','عنوان تماس'),('global-footer','contact.location','تبریز، ایران','Tabriz, Iran','موقعیت'),('global-footer','contact.phone','شماره رسمی در انتظار تأیید','Official number pending approval','تلفن'),('global-footer','contact.email','info@diyarsanat.com','info@diyarsanat.com','ایمیل'),('global-footer','quick_links.title','دسترسی سریع','Quick links','عنوان لینک‌ها')
)
insert into public.site_translations(namespace,translation_key,locale,value,description)
select namespace,key,'fa',fa,description from copy union all select namespace,key,'en',en,description from copy
on conflict(namespace,translation_key,locale) do nothing;

insert into public.site_translations(namespace,translation_key,locale,value,description) values
('home','brands.eyebrow','fa','خانواده برندهای دیار صنعت','عنوان کوچک برندها'),('home','brands.eyebrow','en','Diyar Sanat brand family','Brands eyebrow'),
('home','brands.title','fa','برندهای ما','عنوان برندها'),('home','brands.title','en','Our brands','Brands title'),
('home','brands.description','fa','سه هویت مستقل در مسیر توسعه سبد روانکارها و سیالات خودرویی','توضیح برندها'),('home','brands.description','en','Three distinct identities shaping our automotive fluids portfolio','Brands description'),
('home','media.eyebrow','fa','مجله دیار صنعت','عنوان کوچک رسانه'),('home','media.eyebrow','en','Diyar Sanat journal','Media eyebrow'),
('home','media.title','fa','اخبار و تازه‌ها','عنوان رسانه'),('home','media.title','en','News & insights','Media title'),
('home','media.description','fa','تازه‌ترین مطالب تخصصی، رویدادها و راهنماهای مرتبط با محصولات','توضیح رسانه'),('home','media.description','en','The latest technical articles, events, and product guidance','Media description'),
('home','certificates.title','fa','مجوزها و استانداردهای مجموعه','عنوان گواهینامه‌ها'),('home','certificates.title','en','Company licenses and standards','Certificates title'),
('home','certificates.description','fa','شناسه‌های ثبتی و استانداردهای اعلام‌شده دیار صنعت تبریز','توضیح گواهینامه‌ها'),('home','certificates.description','en','Declared registrations and standards of Diyar Sanat Tabriz','Certificates description'),
('global-footer','newsletter.title','fa','از جدیدترین محصولات و اخبار باخبر شوید','عنوان خبرنامه'),('global-footer','newsletter.title','en','Stay informed about products and news','Newsletter title'),
('global-footer','newsletter.description','fa','با عضویت در خبرنامه، تازه‌های دیار صنعت را دریافت کنید.','توضیح خبرنامه'),('global-footer','newsletter.description','en','Subscribe for the latest updates from Diyar Sanat.','Newsletter description'),
('global-footer','customer_service.title','fa','خدمات مشتریان','عنوان خدمات'),('global-footer','customer_service.title','en','Customer service','Customer service title'),
('global-footer','products.title','fa','محصولات','عنوان محصولات'),('global-footer','products.title','en','Products','Products title')
on conflict(namespace,translation_key,locale) do nothing;

insert into public.faq_items(category_fa,category_en,question_fa,question_en,answer_fa,answer_en,position) values
('خرید و نمایندگی','Purchase & agents','آیا امکان خرید مستقیم از سایت وجود دارد؟','Can I buy directly from this website?','خیر. این وب‌سایت فروشگاه اینترنتی نیست. محصولات را فقط از نمایندگان معتبر معرفی‌شده در صفحه نمایندگان تهیه کنید.','No. This website is not an online store. Buy only from verified representatives listed on the representatives page.',1),
('خرید و نمایندگی','Purchase & agents','نماینده معتبر را چگونه پیدا کنم؟','How do I find a verified representative?','در صفحه نمایندگان، کشور و استان را انتخاب کنید. فقط اطلاعات منتشرشده پس از تأیید رسمی شرکت معتبر است.','Choose your country and province on the representatives page. Only published, company-verified details are official.',2),
('اصالت محصول','Authenticity','چطور محصول اصلی را از نمونه مشکوک تشخیص بدهم؟','How can I identify a suspicious product?','پلمب، کیفیت چاپ، کد تولید و سلامت ظرف را بررسی کنید. هیچ نشانه‌ای به‌تنهایی اصالت را قطعی نمی‌کند و محل خرید معتبر مهم‌ترین معیار است.','Check the seal, print quality, production markings, and container. No single sign proves authenticity; a verified seller is the strongest safeguard.',3),
('اصالت محصول','Authenticity','اگر بسته‌بندی آسیب‌دیده یا ناخوانا بود چه کنم؟','What if the package is damaged or unreadable?','از مصرف محصول خودداری کنید، فاکتور و تصاویر را نگه دارید و موضوع را از مسیر تماس رسمی گزارش دهید.','Do not use the product. Keep the invoice and photos, then report it through the official contact channel.',4),
('انتخاب محصول','Product choice','برای خودروی من کدام روغن مناسب است؟','Which oil is suitable for my vehicle?','دفترچه خودرو و الزامات سازنده اولویت دارد. گرانروی، سطح کیفی و نوع محصول باید با مشخصات خودرو سازگار باشد.','Follow the vehicle manual and manufacturer requirements. Viscosity, performance level, and product type must match the vehicle.',5),
('انتخاب محصول','Product choice','آیا می‌توان روغن‌ها یا ضدیخ‌های متفاوت را مخلوط کرد؟','Can different oils or coolants be mixed?','اختلاط بدون بررسی سازگاری توصیه نمی‌شود. دستورالعمل سازنده خودرو و روش تعویض مناسب را رعایت کنید.','Mixing without a compatibility check is not recommended. Follow the vehicle maker’s guidance and correct change procedure.',6),
('درخواست‌ها','Requests','چگونه وضعیت درخواست خود را پیگیری کنم؟','How can I track my request?','از صفحه پیگیری درخواست و کد درج‌شده در پیام تأیید استفاده کنید.','Use the request-tracking page and the code shown in your confirmation.',7);
