do $$ declare b bigint;c bigint;p bigint;begin
insert into public.brands(code,is_published,position) values('diyar-shimi',true,0) on conflict(code) do update set is_published=true returning id into b;
insert into public.brand_translations(brand_id,locale,name,slug,description) values(b,'fa','دیار شیمی','diyar-shimi','محصولات تخصصی روانکار و سیالات خودرو'),(b,'en','Dyar Shimi','dyar-shimi','Specialist automotive lubricants and fluids') on conflict(brand_id,locale) do update set name=excluded.name,description=excluded.description;
insert into public.product_categories(brand_id,code,icon_key,accent_color,is_published,position) values(b,'engine-oil','oil','#d12632',true,1) on conflict(code) do update set is_published=true returning id into c;
insert into public.product_category_translations(category_id,locale,name,description,slug) values(c,'fa','روغن موتور','روانکاری و محافظت از موتور در شرایط کاری متفاوت','engine-oil'),(c,'en','Engine oil','Lubrication and engine protection across operating conditions','engine-oil') on conflict(category_id,locale) do update set name=excluded.name,description=excluded.description;
insert into public.products(brand_id,category_id,sku,image_url,is_featured,is_published,position,published_at) values(b,c,'DST-10W40','/images/product-engine-oil-dst.png',true,true,1,now()) on conflict(sku) do update set is_published=true returning id into p;
insert into public.product_translations(product_id,locale,name,short_description,key_specification,slug) values(p,'fa','روغن موتور پیشرفته','محافظت پایدار برای کارکرد روزمره موتور','10W-40','advanced-engine-oil-10w40'),(p,'en','Advanced engine oil','Stable protection for everyday engine operation','10W-40','advanced-engine-oil-10w40') on conflict(locale,slug) do update set product_id=excluded.product_id,name=excluded.name,short_description=excluded.short_description,key_specification=excluded.key_specification;
insert into public.product_categories(brand_id,code,icon_key,accent_color,is_published,position) values(b,'gear-oil','gear','#164b82',true,2) on conflict(code) do update set is_published=true returning id into c;
insert into public.product_category_translations(category_id,locale,name,description,slug) values(c,'fa','واسکازین','روانکاری پایدار چرخ‌دنده‌ها و سامانه انتقال قدرت','gear-oil'),(c,'en','Gear oil','Stable lubrication for gears and transmission systems','gear-oil') on conflict(category_id,locale) do update set name=excluded.name;
insert into public.product_categories(brand_id,code,icon_key,accent_color,is_published,position) values(b,'brake-fluid','brake','#c77a10',true,3) on conflict(code) do update set is_published=true returning id into c;
insert into public.product_category_translations(category_id,locale,name,description,slug) values(c,'fa','مایع روغن ترمز','انتقال مطمئن فشار و پایداری عملکرد سامانه ترمز','brake-fluid'),(c,'en','Brake fluid','Reliable pressure transfer and stable braking performance','brake-fluid') on conflict(category_id,locale) do update set name=excluded.name;
insert into public.products(brand_id,category_id,sku,image_url,is_featured,is_published,position,published_at) values(b,c,'DST-DOT4','/images/product-brake-fluid-dst.png',true,true,1,now()) on conflict(sku) do update set is_published=true returning id into p;
insert into public.product_translations(product_id,locale,name,short_description,key_specification,slug) values(p,'fa','مایع روغن ترمز','برای انتقال فشار در سامانه‌های ترمز سازگار','DOT 4','brake-fluid-dot4'),(p,'en','Brake fluid','For pressure transfer in compatible braking systems','DOT 4','brake-fluid-dot4') on conflict(locale,slug) do update set product_id=excluded.product_id,name=excluded.name,short_description=excluded.short_description,key_specification=excluded.key_specification;
insert into public.product_categories(brand_id,code,icon_key,accent_color,is_published,position) values(b,'antifreeze','coolant','#2877bd',true,4) on conflict(code) do update set is_published=true returning id into c;
insert into public.product_category_translations(category_id,locale,name,description,slug) values(c,'fa','ضدیخ و ضدجوش','محافظت از سامانه خنک‌کاری در برابر یخ‌زدگی، جوش و خوردگی','antifreeze'),(c,'en','Antifreeze and coolant','Cooling-system protection from freezing, boiling, and corrosion','antifreeze') on conflict(category_id,locale) do update set name=excluded.name;
insert into public.products(brand_id,category_id,sku,image_url,is_featured,is_published,position,published_at) values(b,c,'DST-AF40','/images/product-antifreeze-dst.png',true,true,1,now()) on conflict(sku) do update set is_published=true returning id into p;
insert into public.product_translations(product_id,locale,name,short_description,key_specification,slug) values(p,'fa','ضدیخ و ضدجوش','محافظت از مدار خنک‌کاری در شرایط دمایی مختلف','-40°C','antifreeze-coolant-40'),(p,'en','Antifreeze and coolant','Cooling-circuit protection across temperature conditions','-40°C','antifreeze-coolant-40') on conflict(locale,slug) do update set product_id=excluded.product_id,name=excluded.name,short_description=excluded.short_description,key_specification=excluded.key_specification;
end $$;
