import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FaqExplorer } from "@/components/support-tools";
import { InnerPageHero } from "@/components/inner-page-hero";
import { isLocale } from "@/lib/i18n";
import { getManagedTranslations } from "@/lib/site-content";
import { createClient } from "@/lib/supabase/server";

type Props = { params: Promise<{ lang: string }> };
const faqFa = [
  { category:"خرید و نمایندگی", question:"آیا امکان خرید مستقیم از سایت وجود دارد؟", answer:"خیر. این وب‌سایت فروشگاه اینترنتی نیست. محصولات را فقط از نمایندگان معتبر معرفی‌شده در صفحه نمایندگان تهیه کنید و پیش از پرداخت، مشخصات فروشنده و کالا را بررسی کنید." },
  { category:"خرید و نمایندگی", question:"نماینده معتبر را چگونه پیدا کنم؟", answer:"در صفحه نمایندگان، کشور و استان را انتخاب کنید. فقط اطلاعاتی که پس از تأیید رسمی شرکت در آن صفحه منتشر شده‌اند معتبر هستند." },
  { category:"اصالت محصول", question:"چطور محصول اصلی را از نمونه مشکوک تشخیص بدهم؟", answer:"یکپارچگی درپوش و پلمب، کیفیت چاپ و نبود غلط املایی، خوانایی شماره بچ یا تولید، مشخصات فنی و سلامت ظرف را کنترل کنید. هیچ نشانه منفردی به‌تنهایی اصالت را قطعی نمی‌کند؛ محل خرید معتبر مهم‌ترین معیار است." },
  { category:"اصالت محصول", question:"اگر بسته‌بندی آسیب‌دیده یا اطلاعات آن ناخوانا بود چه کنم؟", answer:"از مصرف محصول خودداری کنید، فاکتور و تصاویر ظرف را نگه دارید و موضوع را همراه با نام فروشنده از مسیر تماس رسمی شرکت گزارش دهید." },
  { category:"انتخاب محصول", question:"برای خودروی من کدام روغن مناسب است؟", answer:"اولویت با دفترچه راهنمای خودرو و الزامات سازنده است. گرانروی، سطح کیفی و نوع محصول باید دقیقاً با مشخصات خودرو سازگار باشد؛ در صورت تردید با واحد فنی یا نماینده معتبر مشورت کنید." },
  { category:"انتخاب محصول", question:"آیا می‌توان دو روغن یا ضدیخ متفاوت را با هم مخلوط کرد؟", answer:"اختلاط بدون بررسی سازگاری توصیه نمی‌شود. برای تعویض نوع یا برند، دستورالعمل سازنده خودرو و روش تخلیه و شست‌وشوی مناسب را رعایت کنید." },
  { category:"درخواست‌ها", question:"چگونه وضعیت درخواست خود را پیگیری کنم؟", answer:"از صفحه پیگیری درخواست و کد درج‌شده در پیام تأیید استفاده کنید. تا زمان فعال‌شدن اتصال آنلاین، کد را از مسیر صفحه تماس با ما برای واحد مربوط ارسال کنید." },
];
const faqEn = [
  { category:"Purchase & agents", question:"Can I buy directly from this website?", answer:"No. This website is not an online store. Buy only from verified representatives listed on the representatives page and check the seller and product before payment." },
  { category:"Purchase & agents", question:"How do I find a verified representative?", answer:"Choose your country and province on the representatives page. Only details published there after company verification should be treated as official." },
  { category:"Authenticity", question:"How can I identify a suspicious product?", answer:"Check cap and seal integrity, print quality and spelling, readable batch or production markings, technical details, and container condition. No single sign proves authenticity; buying from a verified seller is the strongest safeguard." },
  { category:"Authenticity", question:"What if the package is damaged or unreadable?", answer:"Do not use the product. Keep the invoice and photos, then report the seller and product through the official contact channel." },
  { category:"Product choice", question:"Which oil is suitable for my vehicle?", answer:"Follow the vehicle manual and manufacturer requirements. Viscosity, performance level, and product type must match the vehicle; ask the technical team or a verified representative when uncertain." },
  { category:"Product choice", question:"Can different oils or coolants be mixed?", answer:"Mixing without a compatibility check is not recommended. Follow the vehicle maker’s guidance and the correct drain or flush procedure when changing product type or brand." },
  { category:"Requests", question:"How can I track my request?", answer:"Use the request-tracking page and the code in your confirmation. Until online lookup is connected, send the code to the relevant team through the contact page." },
];
export async function generateMetadata({params}:Props):Promise<Metadata>{const{lang}=await params;if(!isLocale(lang))return{};const fa=lang==="fa";return{title:fa?"پرسش‌های متداول | دیار صنعت تبریز":"Frequently asked questions | Diyar Sanat Tabriz",description:fa?"پاسخ پرسش‌های خرید، نمایندگان، اصالت کالا، انتخاب روانکار و پیگیری درخواست‌های دیار صنعت.":"Answers about purchasing, verified representatives, product authenticity, lubricant selection, and request tracking.",alternates:{canonical:`/${lang}/faq`,languages:{fa:"/fa/faq",en:"/en/faq"}}};}
export default async function FaqPage({params}:Props){const{lang}=await params;if(!isLocale(lang))notFound();const fa=lang==="fa";const[{data},managed]=await Promise.all([(await createClient()).from("faq_items").select("category_fa,category_en,question_fa,question_en,answer_fa,answer_en").eq("is_published",true).order("position"),getManagedTranslations(lang,"faq")]);const dbItems=(data??[]).map(item=>({category:fa?item.category_fa:item.category_en,question:fa?item.question_fa:item.question_en,answer:fa?item.answer_fa:item.answer_en}));const items=dbItems.length?dbItems:(fa?faqFa:faqEn);const t=(key:string,fallback:string)=>managed[key]?.trim()||fallback;const faqJsonLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map((item)=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))};return <main id="main-content" className="support-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqJsonLd).replace(/</g,"\\u003c")}}/><InnerPageHero locale={lang} current={fa?"پرسش‌های متداول":"FAQ"} eyebrow={t("hero.eyebrow",fa?"مرکز پاسخ‌گویی":"Help center")} title={t("hero.title",fa?"پاسخ سؤال‌های مهم، پیش از انتخاب":"Answers before you choose")} description={t("hero.description",fa?"درباره خرید از نمایندگان، اصالت کالا، انتخاب محصول و پیگیری درخواست پاسخ‌های روشن پیدا کنید.":"Clear guidance on verified purchasing, authenticity, product choice, and tracking.")}/><FaqExplorer locale={lang} items={items}/><aside className="container-wide support-cta"><div><span>{fa?"پاسخ خود را پیدا نکردید؟":"Still need help?"}</span><h2>{fa?"پرسش تخصصی را با واحد فنی در میان بگذارید":"Ask our technical team"}</h2></div><Link className="button button-primary" href={`/${lang}/contact`}>{fa?"تماس با ما":"Contact us"}</Link></aside></main>}
